### ISSUE TITLE
Apllication is not maximized at start

### ISSUE THREAD

**Issue by edeforas** [edeforas/Astree#33]
Need to click on the title left icon twice

Under Windows and linux
@Symbian9

**Comment by Symbian9** [comment]
With 1.22 AppImage build under Linux I could reproduce such issue (display 1280x800)

There few suggestions:

- Astree by default (on clean install) should run in maximized window mode (or in minimal window mode `1024x768`..`1280x720` px)
- Astree should be able work on `1024x768` px (or at least `1280x720` px);
- Astree should write window state on exit to config file (related https://github.com/edeforas/Astree/issues/31).

**Comment by edeforas** [comment]
seems ok with a nasty Qt bug fix , applying a bigger size than screen before mximizing
