### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Symbian9** [edeforas/Astree#35]
### Actual behavior

As I can see in `README.md` as license mentioned `GPL`

> The code sources is GPL, using Qt, feel free to contribute!

But according `LICENSE.txt` source code licensed under `LGPL-3.0` (aka `GNU LGPLv3`, `GNU Lesser General Public License v3.0`):

- https://github.com/edeforas/Astree/blob/master/LICENSE.txt

### Expected behavior

Need set properly license and correct `README.md` and `LICENSE.txt`

I suggest that whole project source code should be licensed under `GPL-3.0` (aka `GNU GPLv3`; `GNU General Publice License v3.0`).

Mostly FLOSS app use `GNU GPLv3` for code (if its not a lib); but there are some projects that use `GNU LGPLv3` for whole project, such as *FreeCAD*:

- https://wiki.freecadweb.org/License

If you set `LGPL-3.0` as *Astree* license for a reason, please provide more info.

**Comment by edeforas** [comment]
Thanks, set all under LGPL V3.0 ; its free, but I have no problem if it is used in a product someday
